### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by uDEV2019**

### CODE REVIEW

**Comment by MouriNaruto** [comment]
First, I want to say thank you very much. But I think all `comment` should be kept English for make it better to maintenance in the future. Here is an example.

image

Kenji Mouri

**Comment by SakuraNeko** [comment]
> First, I want to say thank you very much. But I think all should be kept English for make it better to maintenance in the future. Here is an example.`comment`
> 
> Kenji Mouri

@MouriNaruto Considering the user's right to choose, I think it should be localized after the feature is stabilized, especially when contributors take the initiative to submit suggestions.

**Comment by MouriNaruto** [comment]
> @MouriNaruto Considering the user's right to choose, I think it should be localized after the feature is stabilized, especially when contributors take the initiative to submit suggestions.

I think it's OK to merge i18n support at every time. If new features will be added in the future. It will use English and any contributor can create a new PR for localization.

Kenji Mouri

**Comment by uDEV2019** [comment]
> First, I want to say thank you very much. But I think all `comment` should be kept English for make it better to maintenance in the future. Here is an example.
>
> Kenji Mouri

Changed the comments back to english.

**Comment by MouriNaruto** [comment]
Thank you very much. I have merge it.

Kenji Mouri

**Pull request merged**
